Table configuraciones{
id int [pk,increment]
nombre varchar
descripcion varchar
direccion varchar
telfono varchar
divisa varchar
correo_electronico varchar
web varchar
logo varchar
}

Table gestiones{
id int [pk,increment]
nombre varchar
}

Table niveles{
id int [pk,increment]
nombre varchar
}

Table turnos{
id int [pk,increment]
nombre varchar
}

Table periodos{
id int [pk,increment]
nombre varchar
getion_id int [ref: > gestiones.id]
}

Table grados{
id int [pk,increment]
nombre varchar
nivel_id int [ref: > niveles.id] 
}

Table paralelos{
id int [pk,increment]
nombre varchar
grado_id int [ref: > grados.id]
}

Table materias{
id int [pk,increment]
nombre varchar

}

